language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - pip install flask 
  - pip install logging
  - pip install json
  - pip install socket
  - pip install unittest
  - pip install requests
  
script: test_ser.py # run tests

